# Generated by Django 5.0.1 on 2024-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathc2', '0007_alter_testimonial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default='software development', max_length=255),
        ),
    ]
