# Generated by Django 5.0.1 on 2024-02-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathc2', '0006_alter_testimonial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Hafeex', max_length=255),
        ),
    ]
