# Generated by Django 5.0.1 on 2024-02-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathc2', '0003_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default=2, upload_to='testimonials/'),
            preserve_default=False,
        ),
    ]
